Add base class contract to renders
robocin/rSoccer pull request #60
Opened 2023-08-23 14:48 UTC by fnalmeidap

This change adds a base `BaseRender` class to new renders override implementation. It is intended to provide extensibility from the already created rendering algorithms implemented in the library.

- Adds `BaseRender` class to be followed by newly added renders.
- Adds `Render2D` to implement Robocup Soccer Simulation 2D rendering objects.
- Adds `RenderParam2D` dataclass as a param aggregator from `Render2D` class.

2023-08-23 17:43 UTC, goncamateus requested changes

2023-08-23 17:43 UTC, goncamateus commented on rsoccer_gym/Render/Render2D.py
> +class Render2D(BaseRender):
Just change this name to something like "RenderSim2D"

2023-09-06 20:20 UTC, bonnaborsoi approved these changes

2023-11-13 02:42 UTC, goncamateus commented
We will be following [gymnasium](https://github.com/Farama-Foundation/Gymnasium) idea.
The renderer will not be described as a class but function (e.g. [LunarLander](https://github.com/Farama-Foundation/Gymnasium/blob/8333df8666811d1d0f87f1ca71803cc58bcf09c6/gymnasium/envs/box2d/lunar_lander.py#L678).
Closing for now.

2023-11-13 02:42 UTC, closed without merging